--liquibase formatted sql

--changeset mrmasterz:2021-01-13-003-books
CREATE TABLE BOOKS(
    BOOK_ID BIGINT SERIAL PRIMARY KEY,
    TITLE VARCHAR(255),
    AUTHOR_ID BIGINT REFERENCES AUTHORS,
    GENRE_ID BIGINT REFERENCES GENRES
    )