version: "3"
services:
  postgresdb:
    container_name: 35-hystrix-postgres
    image: library/postgres:13.2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    networks: 
      - library-app

  library-app:
    container_name: 35-spring-netflix-hystrix-library-app
    image:  35-spring-netflix-hystrix-library-app:v1
    depends_on:
      - postgresdb
    ports:
      - 8080:8080
    volumes:
      - ./logs:/opt/project/logs:rw
    networks:
      - library-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/library
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

networks:
  library-app: