spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

liquibase:
  enabled: true
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/library
  user: user
  password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

logging:
  level:
    root: INFO    # default
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){blue} %clr(:){faint} %m%n%wEx"
    file: "%d %p %C{1.} [%t] %m%n"
  file:
    name: logs/30-spring-boot-actuator.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      fileNamePattern: logs/30-spring-boot-actuator-%d{yyyy-MM-dd}.%i.log.gz
      max-history: 30