DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE AUTHORS(AUTHOR_ID BIGINT SERIAL PRIMARY KEY, AUTHOR VARCHAR(255) UNIQUE);
CREATE TABLE GENRES(GENRE_ID BIGINT SERIAL PRIMARY KEY, GENRE VARCHAR(255) UNIQUE);
CREATE TABLE BOOKS(BOOK_ID BIGINT SERIAL PRIMARY KEY, TITLE VARCHAR(255), AUTHOR_ID BIGINT REFERENCES AUTHORS, GENRE_ID BIGINT REFERENCES GENRES);